ipld-path-cross-explore-patch: fix errors
What IPLD library and method are used for parsing and traversing IPLD
paths?

vet: ./ipldpath.go:134:20: undefined: traversal.ParsePath