WIP first draft of x/git-bundle/
vet: ./main.go:64:22: cannot use packfile (variable of type *object.ObjectIter) as io.Reader value in argument to io.Copy: *object.ObjectIter does not implement io.Reader (missing method Read)