Fix the following error:
# command-line-arguments
./main.go:97:17: cannot use node.Representation() (value of interface type datamodel.Node) as schema.TypedNode value in assignment: datamodel.Node does not implement schema.TypedNode (missing method Representation)